### ISSUE TITLE
[建议]Markdown格式的readme编写提示

### ISSUE THREAD

**Issue by Leo204-LKY** [nclmredtea/NAHGN#1]
# [请查看 GitHub 的这个“项目”](https://github.com/guodongxiaren/README/blob/master/README.md)。  

## 使用这个按钮来查看这篇 `readme.md` 的源代码。
![image](https://user-images.githubusercontent.com/57821066/90528078-d012ca80-e1a4-11ea-86b4-74a5649185e2.png)

**Comment by nclmredtea** [comment]
建议已收到
将会在下一次编辑的时候做出相应的改变
