### ISSUE TITLE
[BUG/建议] Wiki 页面错别字提示 / 语法修正工具推荐（仅供参考）

### ISSUE THREAD

**Issue by Leo204-LKY** [nclmredtea/NAHGN#5]
+ [`Wiki/服务器世界百科/Server1创造服/IridiumSkyblock/概况`](https://github.com/nclmredtea/NAHGN/wiki/服务器世界百科#是由iridiumskyblock插件所生成的空岛世界 "点击将重定向至相关段落")中包含错别字“考研”
+ 请尝试使用[秘塔写作猫](https://xiezuocat.com/#/ "点击将重定向秘塔写作猫")来修正语法错误/获取更优的表达等（ AI 判断结果仅供参考）

**Comment by nclmredtea** [comment]
已经收到建议和BUG反馈
BUG将会在下一次编辑时更正
建议中的"秘塔写作猫"将会进行研究
